### ISSUE TITLE
pinus start -i serverId 单独启动服务启动失败

### ISSUE THREAD

**Issue by marshhj** [node-pinus/pinus#104]
直接是pinus init 创建的工程。
为了分开启动服务，使用 pinus start -i serverId 启动服务。
pomelo 的项目可以用该方式启动。
pinus start -t serverType 启动正常。

错误如下：
$ pinus start -i connector-server-1
[2019-12-01T20:41:51.725] [INFO] pinus - [master-server-1 application.js] application inited: "master-server-1"

[2019-12-01T20:41:51.730] [INFO] pinus - [master-server-1 application.js] "master-server-1" enter before start...

[2019-12-01T20:41:51.731] [INFO] pinus - [master-server-1 application.js] "master-server-1" enter after start...

[2019-12-01T20:41:51.733] [INFO] pinus-admin - [master-server-1 mqttServer.js] [MqttServer] listen on 3005

[2019-12-01T20:41:51.787] [ERROR] pinus - [master-server-1 master.js] masterConsole encounters with error: Error: listen EADDRINUSE :::3005
    at Server.setupListenHandle [as _listen2] (net.js:1336:14)
    at listenInCluster (net.js:1384:12)
    at Server.listen (net.js:1471:7)
    at MqttServer.listen (/Users/hhj/Desktop/Code/pomelo/PlayPinus/game-server/node_modules/pinus-admin/lib/protocol/mqtt/mqttServer.ts:45:21)
    at MasterAgent.listen (/Users/hhj/Desktop/Code/pomelo/PlayPinus/game-server/node_modules/pinus-admin/lib/master/masterAgent.ts:89:21)
    at ConsoleService.start (/Users/hhj/Desktop/Code/pomelo/PlayPinus/game-server/node_modules/pinus-admin/lib/consoleService.ts:154:41)
    at MasterServer.start (/Users/hhj/Desktop/Code/pomelo/PlayPinus/game-server/node_modules/pinus/lib/master/master.ts:51:28)
    at MasterComponent.start (/Users/hhj/Desktop/Code/pomelo/PlayPinus/game-server/node_modules/pinus/lib/components/master.ts:27:21)
    at /Users/hhj/Desktop/Code/pomelo/PlayPinus/game-server/node_modules/pinus/lib/util/appUtil.ts:117:34
    at /Users/hhj/Desktop/Code/pomelo/PlayPinus/game-server/node_modules/async/dist/async.js:3110:16
    at replenish (/Users/hhj/Desktop/Code/pomelo/PlayPinus/game-server/node_modules/async/dist/async.js:1011:17)
    at /Users/hhj/Desktop/Code/pomelo/PlayPinus/game-server/node_modules/async/dist/async.js:1016:9
    at eachLimit$1 (/Users/hhj/Desktop/Code/pomelo/PlayPinus/game-server/node_modules/async/dist/async.js:3196:24)
    at Object.<anonymous> (/Users/hhj/Desktop/Code/pomelo/PlayPinus/game-server/node_modules/async/dist/async.js:1046:16)
    at Object.optComponents (/Users/hhj/Desktop/Code/pomelo/PlayPinus/game-server/node_modules/pinus/lib/util/appUtil.ts:114:11)
    at /Users/hhj/Desktop/Code/pomelo/PlayPinus/game-server/node_modules/pinus/lib/application.ts:534:33Error: 
    at Object.pLogger.(anonymous function) [as error] (/Users/hhj/Desktop/Code/pomelo/PlayPinus/game-server/node_modules/pinus-logger/lib/logger.ts:72:34)
    at ConsoleService.<anonymous> (/Users/hhj/Desktop/Code/pomelo/PlayPinus/game-server/node_modules/pinus/lib/master/master.ts:70:24)
    at ConsoleService.emit (events.js:182:13)
    at MasterAgent.<anonymous> (/Users/hhj/Desktop/Code/pomelo/PlayPinus/game-server/node_modules/pinus-admin/lib/consoleService.ts:432:20)
    at MasterAgent.emit (events.js:182:13)
    at MqttServer.<anonymous> (/Users/hhj/Desktop/Code/pomelo/PlayPinus/game-server/node_modules/pinus-admin/lib/master/masterAgent.ts:97:18)
    at MqttServer.emit (events.js:182:13)
    at Server.<anonymous> (/Users/hhj/Desktop/Code/pomelo/PlayPinus/game-server/node_modules/pinus-admin/lib/protocol/mqtt/mqttServer.ts:53:18)
    at Server.emit (events.js:182:13)
    at emitErrorNT (net.js:1363:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)

**Comment by whtiehack** [comment]
明天我去查一下。

**Comment by whtiehack** [comment]
` pinus start -i serverId  -t serverType`    需要同时指定 -t参数。

**Comment by whtiehack** [comment]
修复了 
https://github.com/node-pinus/pinus/commit/30afc85a0466b0283c6ad7cab8017ffd5ea10e82

 发布npm了 1.3.14
