### ISSUE TITLE
pinus-admin-web 使用问题

### ISSUE THREAD

**Issue by beiyouqgf** [node-pinus/pinus#109]
获取服务器rpc-log的数据的时候报错，换成pomelo-admin-web 就没问题，是协议不同的原因导致的还是本身就有bug.
[2019-12-10T18:27:02.077] [INFO] admin-log - 137: [master-server-1 master.js] {"action":"execute","moduleId":"monitorLog","method":"clientHandler","msg":{"clientId":"browser-1575973597091","username":"monitor"}}
[2019-12-10T18:27:02.080] [ERROR] pinus-admin - 69: [master-server-1 monitorLog.js] fail to run log for Error: unknown server id:undefined
    at MasterAgent.request (D:\project\cnjj-server-ts\node_modules\pinus-admin\lib\master\masterAgent.ts:222:16)
    at MonitorLogModule.clientHandler (D:\project\cnjj-server-ts\node_modules\pinus-admin\lib\modules\monitorLog.ts:67:15)
    at ConsoleService.execute (D:\project\cnjj-server-ts\node_modules\pinus-admin\lib\consoleService.ts:288:23)
    at MasterSocket.onClient (D:\project\cnjj-server-ts\node_modules\pinus-admin\lib\master\masterSocket.ts:164:39)
    at Connection.<anonymous> (D:\project\cnjj-server-ts\node_modules\pinus-admin\lib\master\masterAgent.ts:127:30)
    at Connection.emit (events.js:210:5)
    at Connection.<anonymous> (D:\project\cnjj-server-ts\node_modules\pinus-admin\lib\protocol\mqtt\mqttServer.ts:74:24)
    at Connection.emit (events.js:210:5)
    at Connection.emitPacket (D:\project\cnjj-server-ts\node_modules\mqtt-connection\connection.js:10:8)
    at Connection.emit (events.js:210:5)
    at addChunk (D:\project\cnjj-server-ts\node_modules\readable-stream\lib\_stream_readable.js:291:12)
    at readableAddChunk (D:\project\cnjj-server-ts\node_modules\readable-stream\lib\_stream_readable.js:278:11)
    at Connection.Readable.push (D:\project\cnjj-server-ts\node_modules\readable-stream\lib\_stream_readable.js:245:10)
    at Connection.Duplexify._forward (D:\project\cnjj-server-ts\node_modules\duplexify\index.js:170:26)
    at DestroyableTransform.onreadable (D:\project\cnjj-server-ts\node_modules\duplexify\index.js:134:10)
    at DestroyableTransform.emit (events.js:210:5)
    at emitReadable_ (D:\project\cnjj-server-ts\node_modules\readable-stream\lib\_stream_readable.js:504:10)
    at emitReadable (D:\project\cnjj-server-ts\node_modules\readable-stream\lib\_stream_readable.js:498:62)
    at addChunk (D:\project\cnjj-server-ts\node_modules\readable-stream\lib\_stream_readable.js:298:29)
    at readableAddChunk (D:\project\cnjj-server-ts\node_modules\readable-stream\lib\_stream_readable.js:278:11)
    at DestroyableTransform.Readable.push (D:\project\cnjj-server-ts\node_modules\readable-stream\lib\_stream_readable.js:245:10)
    at DestroyableTransform.Transform.push (D:\project\cnjj-server-ts\node_modules\readable-stream\lib\_stream_transform.js:148:32)Error: 
    at Object.pLogger.<computed> [as error] (D:\project\cnjj-server-ts\node_modules\pinus-logger\lib\logger.ts:72:34)
    at D:\project\cnjj-server-ts\node_modules\pinus-admin\lib\modules\monitorLog.ts:69:24
    at MasterAgent.request (D:\project\cnjj-server-ts\node_modules\pinus-admin\lib\master\masterAgent.ts:222:13)
    at MonitorLogModule.clientHandler (D:\project\cnjj-server-ts\node_modules\pinus-admin\lib\modules\monitorLog.ts:67:15)
    at ConsoleService.execute (D:\project\cnjj-server-ts\node_modules\pinus-admin\lib\consoleService.ts:288:23)
    at MasterSocket.onClient (D:\project\cnjj-server-ts\node_modules\pinus-admin\lib\master\masterSocket.ts:164:39)
    at Connection.<anonymous> (D:\project\cnjj-server-ts\node_modules\pinus-admin\lib\master\masterAgent.ts:127:30)
    at Connection.emit (events.js:210:5)
    at Connection.<anonymous> (D:\project\cnjj-server-ts\node_modules\pinus-admin\lib\protocol\mqtt\mqttServer.ts:74:24)
    at Connection.emit (events.js:210:5)
    at Connection.emitPacket (D:\project\cnjj-server-ts\node_modules\mqtt-connection\connection.js:10:8)
    at Connection.emit (events.js:210:5)
    at addChunk (D:\project\cnjj-server-ts\node_modules\readable-stream\lib\_stream_readable.js:291:12)
    at readableAddChunk (D:\project\cnjj-server-ts\node_modules\readable-stream\lib\_stream_readable.js:278:11)
    at Connection.Readable.push (D:\project\cnjj-server-ts\node_modules\readable-stream\lib\_stream_readable.js:245:10)
    at Connection.Duplexify._forward (D:\project\cnjj-server-ts\node_modules\duplexify\index.js:170:26)
    at DestroyableTransform.onreadable (D:\project\cnjj-server-ts\node_modules\duplexify\index.js:134:10)
    at DestroyableTransform.emit (events.js:210:5)
    at emitReadable_ (D:\project\cnjj-server-ts\node_modules\readable-stream\lib\_stream_readable.js:504:10)
    at emitReadable (D:\project\cnjj-server-ts\node_modules\readable-stream\lib\_stream_readable.js:498:62)
    at addChunk (D:\project\cnjj-server-ts\node_modules\readable-stream\lib\_stream_readable.js:298:29)
    at readableAddChunk (D:\project\cnjj-server-ts\node_modules\readable-stream\lib\_stream_readable.js:278:11)

**Comment by whtiehack** [comment]
https://github.com/whtiehack/pomelo-admin-web-new  
用这个。这个是测试过的。
