### ISSUE TITLE
creator继承pinus模拟器调试和打安卓包报错

### ISSUE THREAD

**Issue by lcax200000** [node-pinus/pinus#161]
creator 集成pinus ，导入build.js使用模拟器方式运行报错
**Simulator: E/jswrapper (749): ScriptEngine::evalString catch exception:**
    at HTMLElement.print-simulator-log (D:\CocosDashboard_1.0.10\resources\.editors\Creator\2.4.3\resources\app.asar\editor\builtin\scene\panel\messages\scene.js:1:1606)
    at Object.e._dispatch (D:\CocosDashboard_1.0.10\resources\.editors\Creator\2.4.3\resources\app.asar\editor-framework\lib\renderer\panel.js:1:1876)
    at EventEmitter.<anonymous> (D:\CocosDashboard_1.0.10\resources\.editors\Creator\2.4.3\resources\app.asar\editor-framework\lib\renderer\ipc.js:1:2952)
    at EventEmitter.emit (events.js:194:13)
    at EventEmitter.emit (domain.js:469:20)
    at EventEmitter.topLevelDomainCallback (domain.js:124:23)
**Simulator: E/jswrapper (281): ERROR: Uncaught Error: Failed to require "assets/internal/index.js" from "root", location: E:/basketball/assets/Script/Net/build.js:0:0**
STACK:
[0]require@E:/basketball/assets/Script/Net/build.js:25
[1]anonymous@jsb-adapter/jsb-engine.js:3340
[2]download@jsb-adapter/jsb-engine.js:3351
[3]downloadScript@jsb-adapter/jsb-engine.js:3339
[4]anonymous@jsb-adapter/jsb-engine.js:3507
[5]anonymous@jsb-adapter/jsb-engine.js:3180
[6]readFile@jsb-adapter/jsb-engine.js:3146
[7]readJson@jsb-adapter/jsb-engine.js:3168
[8]parseJson@jsb-adapter/jsb-engine.js:3465
[9]download@jsb-adapter/jsb-engine.js:3351
[10]downloadJson@jsb-adapter/jsb-engine.js:3477
[11]downloadBundle@jsb-adapter/jsb-engine.js:3499
[12]invoke@src/cocos2d-jsb.js:22012
[13]process@src/cocos2d-jsb.js:22022
[14]retry@src/cocos2d-jsb.js:23609
[15]download@src/cocos2d-jsb.js:22046
[16]load@src/cocos2d-jsb.js:22720
[17]fetch@src/cocos2d-jsb.js:22553
[18]_flow@src/cocos2d-jsb.js:23001
[19]async@src/cocos2d-jsb.js:22996
    at HTMLElement.print-simulator-log (D:\CocosDashboard_1.0.10\resources\.editors\Creator\2.4.3\resources\app.asar\editor\builtin\scene\panel\messages\scene.js:1:1606)
    at Object.e._dispatch (D:\CocosDashboard_1.0.10\resources\.editors\Creator\2.4.3\resources\app.asar\editor-framework\lib\renderer\panel.js:1:1876)
    at EventEmitter.<anonymous> (D:\CocosDashboard_1.0.10\resources\.editors\Creator\2.4.3\resources\app.asar\editor-framework\lib\renderer\ipc.js:1:2952)
    at EventEmitter.emit (events.js:194:13)
    at EventEmitter.emit (domain.js:469:20)
    at EventEmitter.topLevelDomainCallback (domain.js:124:23)

**Comment by whtiehack** [comment]
https://github.com/search?q=pomelo+creator

找几个试试.

**Comment by lcax200000** [comment]
可以了~多谢
