### ISSUE TITLE
Master高可用bug及其fix方案，烦请大佬修改

### ISSUE THREAD

**Issue by qinfanheaven** [node-pinus/pinus#169]
环境:
CentOS 7.9 + NodeJs v12.22.1
1、先说一下zookeeper，应该必要集群部署，反正所有Server都是连接同一个，且其是否是Leader是无所谓的，zookeeper仅仅用来做资源互斥访问的。保证所有Server获取到的是同一个Master，主Master先启动先占用，宕机后其他从Master去GetLock争夺主位。这样理解是否正确？
2、`pinus masterha` 直接从控制台执行的话，sshrun会报错，只能手动注释Master所在服务器里面的代码：
```
function sshrun(cmd, host, cb) {
    let args = [];
    args.push(host);
    // 注释下面三行，因为此时app并没有创建
    let ssh_params = pinus_1.pinus.app.get(Constants.RESERVED.SSH_CONFIG_PARAMS);
    if (!!ssh_params && Array.isArray(ssh_params)) {
        args = args.concat(ssh_params);
    }
    args.push(cmd);
    logger.info('Executing ' + cmd + ' on ' + host + ':22');
    spawnProcess(Constants.COMMAND.SSH, host, args, cb);
    return;
}
```
3、pomelo-masterha-plugin的reconnect方法中，执行了一下重连操作：
`monitor!.reconnect(JSON.parse(masterInfo));`
但是mqttClient中的socket: MqttConnect已经被置null，而reconnect会先执行close，报错如下：
```
 Caught exception: TypeError: Cannot read property 'disconnect' of null
    at MqttClient.close (/data/PinusServerDev/game-server/node_modules/pinus-admin/lib/protocol/mqtt/mqttClient.ts:243:21)
    at MqttClient.disconnect (/data/PinusServerDev/game-server/node_modules/pinus-admin/lib/protocol/mqtt/mqttClient.ts:237:14)
    at MonitorAgent.close (/data/PinusServerDev/game-server/node_modules/pinus-admin/lib/monitor/monitorAgent.ts:199:21)
    at ConsoleService.stop (/data/PinusServerDev/game-server/node_modules/pinus-admin/lib/consoleService.ts:189:20)
    at Monitor.stop (/data/PinusServerDev/game-server/node_modules/pinus/lib/monitor/monitor.ts:76:29)
    at Monitor.reconnect (/data/PinusServerDev/game-server/node_modules/pinus/lib/monitor/monitor.ts:86:14)
    at MonitorComponent.reconnect (/data/PinusServerDev/game-server/node_modules/pinus/lib/components/monitor.ts:28:22)
    at /data/PinusServerDev/game-server/node_modules/@cnpm-kuzi/pinus-masterha-plugin/dist/lib/components/PinusMasterZookeeper.js:163:21
    at Object.invokeCallback [as default] (/data/PinusServerDev/game-server/node_modules/@cnpm-kuzi/pinus-masterha-plugin/dist/lib/util/utils.js:9:12)
    at /data/PinusServerDev/game-server/node_modules/@cnpm-kuzi/pinus-masterha-plugin/dist/lib/components/PinusMasterZookeeper.js:174:28
    at /data/PinusServerDev/game-server/node_modules/node-zookeeper-client/index.js:166:26
    at Object.async.whilst (/data/PinusServerDev/game-server/node_modules/node-zookeeper-client/node_modules/async/lib/async.js:627:13)
    at /data/PinusServerDev/game-server/node_modules/node-zookeeper-client/node_modules/async/lib/async.js:623:23
    at /data/PinusServerDev/game-server/node_modules/node-zookeeper-client/index.js:146:21
    at Object.callback (/data/PinusServerDev/game-server/node_modules/node-zookeeper-client/index.js:622:17)
    at ConnectionManager.onSocketData (/data/PinusServerDev/game-server/node_modules/node-zookeeper-client/lib/ConnectionManager.js:563:35)Error: 
    at Logger.pLogger.<computed> [as error] (/data/PinusServerDev/game-server/node_modules/pinus-logger/lib/logger.ts:70:34)
    at process.<anonymous> (/data/PinusServerDev/game-server/app.ts:150:13)
    at process.emit (events.js:326:22)
    at process._fatalException (internal/process/execution.js:165:25)
```
临时解决方案：
```
            let agent: MonitorAgent = self.app.components.__monitor__?.monitor.monitorConsole.agent as MonitorAgent;
            // 修改disconnect逻辑
            agent.socket.disconnect = function() {
                self.logger.info('MonitorAgent mqttClient custom disconnect call');
                this.connected = false;
                this.closed = true;
                // 暂停重连，马上重建连接
                clearTimeout(this.reconnectId);
                clearTimeout(this.timeoutId);
                this.connectedTimes = 1;
                // 增加判断
                if (this.socket) {
                    this.socket.disconnect();
                }
            }

            monitor!.reconnect(JSON.parse(masterInfo));
```
经测试，kill主Master之后可以切换到下一个从Master

**Comment by whtiehack** [comment]
可以提交个pr

**Comment by qinfanheaven** [comment]
sshrun这个函数不敢动，我自己是没有什么ssh_params，如果注释掉，可能会影响有ssh有参数传递需求的项目。
mqttClient已提pr

**Comment by whtiehack** [comment]
重连这个合并了哈

sshrun我也不敢乱动哈.我现在没有用到的场景,所以没研究

**Comment by whtiehack** [comment]
#172

**Comment by guhaizhous** [comment]
[WARN] pinus - [master-server-1 watchdog.js] all servers startup in 13531 ms
[2023-07-25T18:13:33.765] [ERROR] pinus-admin - [console-server-1 mqttClient.js] mqtt socket is disconnect, remote server host: 127.0.0.1, 
port: 3005Error:

这个mqtt 怎么会报错，是什么原因，有哪位遇到过吗，请教了！
