### ISSUE TITLE
TypeError: utils.promisify is not a function

### ISSUE THREAD

**Issue by canplay** [node-pinus/pinus#17]
Caught exception: TypeError: utils.promisify is not a function
    at new Application (D:\Workspaces\Code\pinus\HelloWorld\game-server\node_modules\pinus\lib\application.ts:1132:20)
    at Pinus.createApp (D:\Workspaces\Code\pinus\HelloWorld\game-server\node_modules\pinus\lib\pinus.ts:138:19)
    at Object.<anonymous> (D:\Workspaces\Code\pinus\HelloWorld\game-server\app.ts:14:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:496:3

新建的HelloWorld报错，不知为何

**Comment by mybios** [comment]
要用node.js的8.x版本，建议选稳定最新版
