### ISSUE TITLE
启动时报错Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by gz65555** [node-pinus/pinus#28]
```
Caught exception: TypeError: Cannot read property 'id' of undefined
    at processArgs (/Users/husong/WebstormProjects/work/PinusTest/game-server/node_modules/pinus/lib/util/appUtil.ts:201:46)
    at Object.defaultConfiguration (/Users/husong/WebstormProjects/work/PinusTest/game-server/node_modules/pinus/lib/util/appUtil.ts:25:5)
    at Application.init (/Users/husong/WebstormProjects/work/PinusTest/game-server/node_modules/pinus/lib/application.ts:186:17)
    at Pinus.createApp (/Users/husong/WebstormProjects/work/PinusTest/game-server/node_modules/pinus/lib/pinus.ts:139:13)
    at Object.<anonymous> (/Users/husong/WebstormProjects/work/PinusTest/game-server/app.ts:14:17)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)

貌似是app.getMaster()是undefined

**Comment by GHXiaHou90** [comment]
我这也出现了，，不过我是使用指令 npm run start 后出现的，正常的cd dist => node app.js 步骤启动就没问题！

**Comment by GHXiaHou90** [comment]
是因为用windows系统环境下才出现的吗？

**Comment by whtiehack** [comment]
是因为 没找到 config 里的 master.json

**Comment by tonyzzp** [comment]
我第一次启动正常 然后我给强行结束了进程  再启动就这样了。
后来我 
git checkout . 
git reset .
git reset --hard origin/master
再重新编译就正常了。
