### ISSUE TITLE
服务端提示这个错误，这是什么原因

### ISSUE THREAD

**Issue by yasuoganliang** [node-pinus/pinus#37]
[2018-08-06T11:01:34.237] [ERROR] pinus-admin - [gate-server-1 mqttClient.js] mqtt rpc client checkKeepAlive error timeout for 120000Error
    at Object.pLogger.(anonymous function) [as error] (D:\gameServer\pinus\wolong-0804\wolong\game-server\node_modules\pinus-logger\lib\logger.ts:59:34) 
    at MqttClient.checkKeepAlive(D:\gameServer\pinus\wolong0804\wolong\gameserver\node_modules
\pinus-admin\lib\protocol\mqtt\mqttClient.ts:221:28)
    at Timeout._onTimeout (D:\gameServer\pinus\wolong0804\wolong\gameserver\node_modules\pinus-admin\lib\protocol\mqtt\mqttClient.ts:207:18)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)

**Comment by whtiehack** [comment]
没明白，可否描述详细点

**Comment by yasuoganliang** [comment]
每次启动服务后过段时间之后会报这个错 `mqtt rpc client checkKeepAlive error timeout for 120000Error`，之后连接就自动断开了。配置我只改了端口和 ip ，编译的时候好像也有这个提示这个模块错误 `mqtt-connection`。是版本问题还是什么原因呢？

**Comment by whtiehack** [comment]
你动过配置了？那应该是你配置问题。好好找找配置原因。  新建个项目做对比。

**Comment by yasuoganliang** [comment]
没动配置。用的官网的配置。

**Comment by whtiehack** [comment]
`pinus init` 用这个命令新建一个项目来测试。

**Comment by yasuoganliang** [comment]
`pinus init ` 也有这样的问题
```
[2018-08-26T11:11:39.254] [ERROR] pinus-admin - [master-server-1 mqttClient.js] mqtt rpc client checkKeepAlive error timeout for 120000Error
    at Object.pLogger.(anonymous function) [as error] (/home/yujinsheng/temp/pinus/wolong/game-server/node_modules/pinus-logger/lib/logger.ts:59:34)
    at MqttClient.checkKeepAlive (/home/yujinsheng/temp/pinus/wolong/game-server/node_modules/pinus-admin/lib/protocol/mqtt/mqttClient.ts:221:28)
    at Timeout._onTimeout (/home/yujinsheng/temp/pinus/wolong/game-server/node_modules/pinus-admin/lib/protocol/mqtt/mqttClient.ts:207:18)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
```

**Comment by whtiehack** [comment]
应该是哪里配置有问题。你把 examples里的示例拿出来跑看看。

**Comment by yasuoganliang** [comment]
okok

**Comment by whtiehack** [comment]
启动的时候有什么报错么。

**Comment by yasuoganliang** [comment]
只有这一个错误，启动之后不操作挂着也会有这个问题

**Comment by whtiehack** [comment]
你把完整的启动日志发出来看看。

**Comment by whtiehack** [comment]
`pinus-admin - [gate-server-1 consoleService.js] try to connect master: "gate", "xxx", 3012`你的master端口改了？而且ip是外网？

**Comment by yasuoganliang** [comment]
okok， 明白了，多谢多谢

**Comment by Jason8Aaron** [comment]
nodejs版本升级到12.8.0经常出现。以前8.9.4的时候没有出现过？都是win10。

**Comment by whtiehack** [comment]
win10有很多人反映的确有问题。有大佬说跟win10系统有关系，难道跟node版本有关系？  你换回 8.9.4看还出现么？

**Comment by Jason8Aaron** [comment]
我明天试下，一个小时内应该就没问题

发自我的 iPhone

**Comment by Jason8Aaron** [comment]
我试过了，确实是Node版本问题，有些东西可能要升级一下，毕竟快7年了😅应该大多升级个依赖包就可以了吧。
发自我的 iPhone

**Comment by whtiehack** [comment]
有空的话，建议试一下10.x的有问题没有。12有问题就不想研究了。

**Comment by Jason8Aaron** [comment]
试了一下10.16.2也有问题。。。

**Comment by whtiehack** [comment]
好。我研究一下。10.16.2
