### ISSUE TITLE
单独启动的游戏服务，可以自动加入到集群，但是尝试进入游戏报错fail to forward message:TypeError: Cannot read property 'msgRemote' of undefined

### ISSUE THREAD

**Issue by Jasonlbf** [node-pinus/pinus#44]
用pomelo start -e production -d . 命令启动了一个gate，两个connector，2个游戏。 之后用NODE_ENV=production node app.js host="127.0.0.1" port=6950 frontend=false serverType="game3" id="game3-server-1" 命令启动了另一个游戏。
master发现了这个游戏“master watchdog notify to monitor success, id: game3-server-1 ........”。
game3也收到相关信息“game3-server-1 receive replaceServer signal: {"action":"replaceServer","servers":{"scheduleJ.............”。
但是无法从大厅进入游戏，报错“fail to forward message:TypeError: Cannot read property 'msgRemote' of undefined”
请问：是哪里配置不对吗？

**Comment by Jasonlbf** [comment]
pomelo版本2.2.5

**Comment by whtiehack** [comment]
因为这个配置的服务器已经启动了。如果需要添加配置文件里没有的服，需要使用 pinus add。

**Comment by whtiehack** [comment]
理论上你直接改端口，服ID来启动进程，就是一个服。

你既然是用docker启动，那么建议你master进程单独启动比较好。

启动master：
```
node app.js mode=stand-alone
```

启动connector:
```
node app.js env=development  id=connector-server-1  host=127.0.0.1  port=3150  clientHost=192.168.1.10  clientPort=3010  frontend=true  serverType=connector
```
启动main:

```
node app.js env=development  id=main-server-1  host=127.0.0.1  port=5100  serverType=main 
```

其它进程的启动方式可以参考 connector，和main的启动参数，只需要更改 host port, id ， 这些进程在配置里是可以不用存在的。

**Comment by linguitang** [comment]
使用` node tsrun.js mode=stand-alone env=development id=master  host=127.0.0.1 port=7034  serverType=master`启动，报错
```
master         | [2019-10-24T01:07:59.743] [INFO] pinus - [master application.js] application inited: "master"
master         | [2019-10-24T01:07:59.746] [INFO] pinus - [master application.js] "master" enter before start...
master         | [2019-10-24T01:07:59.747] [INFO] pinus - [master application.js] "master" enter after start...
master         | [2019-10-24T01:07:59.748] [INFO] pinus-admin - [master mqttServer.js] [MqttServer] listen on 7034
master         | [2019-10-24T01:07:59.751] [INFO] pinus-admin - [master consoleService.js] try to connect master: "master", "192.168.0.105", 7034
master         | [2019-10-24T01:07:59.831] [ERROR] pinus-admin - [master mqttClient.js] mqtt socket is error, remote server host: 192.168.0.105, port: 7034Error: 
master         |     at Object.pLogger.<computed> [as error] (/usr/local/server/node_modules/pinus-logger/lib/logger.ts:72:34)
master         |     at Connection.<anonymous> (/usr/local/server/node_modules/pinus-admin/lib/protocol/mqtt/mqttClient.ts:113:20)
master         |     at Connection.emit (events.js:210:5)
master         |     at Socket.emit (events.js:210:5)
master         |     at emitErrorNT (internal/streams/destroy.js:92:8)
master         |     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
master         |     at processTicksAndRejections (internal/process/task_queues.js:80:21)
master         | [2019-10-24T01:07:59.832] [INFO] pinus-admin - [master mqttClient.js] exit ...
master exited with code 0

```
