### ISSUE TITLE
运行事例报错gate-server-1Caught exception: TypeError: ParserIncomingMessage is not a constructor

### ISSUE THREAD

**Issue by disunit** [node-pinus/pinus#45]
[2018-10-26T13:40:41.282] [WARN] pinus - [master-server-1 watchdog.js] all servers startup in 405 ms

[2018-10-26T13:40:41.287] [INFO] logger - [master-server-1 console] Started Robot Master Http server on : http://localhost:8776

[2018-10-26T13:40:41.285] [WARN] logger - [connector-server-1 console] after start all server, use route dictionary :
 chat.chatHandler.send
connector.entryHandler.enter
connector.entryHandler.onUserLeave
gate.gateHandler.queryEntry

[2018-10-26 13:41:41] INFO: Nodes: 0, WebClients: 0

[2018-10-26T13:42:21.274] [ERROR] logger - [gate-server-1 console] gate-server-1Caught exception: TypeError: ParserIncomingMessage is not a constructor
    at HTTPParser.parserOnHeadersComplete (_http_common.js:81:21)
    at socketOnData (_http_server.js:470:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at WSProcessor.add (/Users/disunits/Downloads/pinus-master/examples/websocket-chat/game-server/node_modules/pinus/lib/connectors/hybrid/wsprocessor.ts:44:20)
    at HybridSwitcher.processHttp (/Users/disunits/Downloads/pinus-master/examples/websocket-chat/game-server/node_modules/pinus/lib/connectors/hybrid/switcher.ts:120:19)
    at Socket.socket.once (/Users/disunits/Downloads/pinus-master/examples/websocket-chat/game-server/node_modules/pinus/lib/connectors/hybrid/switcher.ts:99:22)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:601:20)Error
    at Object.pLogger.(anonymous function) [as error] (/Users/disunits/Downloads/pinus-master/examples/websocket-chat/game-server/node_modules/pinus-logger/lib/logger.ts:59:34)
    at process.<anonymous> (/Users/disunits/Downloads/pinus-master/examples/websocket-chat/game-server/preload.ts:33:17)
    at emitOne (events.js:116:13)
    at process.emit (events.js:211:7)
    at process._fatalException (bootstrap_node.js:391:26)

**Comment by whtiehack** [comment]
换版本。 8.11.x
https://github.com/nodejs/node/issues/22857
