### ISSUE TITLE
simple example  websocket无法连接

### ISSUE THREAD

**Issue by tonyzzp** [node-pinus/pinus#70]
[2019-03-19T10:37:48.496] [ERROR] logger - [connector-server-1 console] Caught exception: TypeError: ParserIncomingMessage is not a constructor
    at HTTPParser.parserOnHeadersComplete (_http_common.js:81:21)
    at socketOnData (_http_server.js:470:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at WSProcessor.add (D:\github\pinus\examples\simple-example\game-server\node_modules\pinus\lib\connectors\hybrid\wsprocessor.ts:44:20)
    at HybridSwitcher.processHttp (D:\github\pinus\examples\simple-example\game-server\node_modules\pinus\lib\connectors\hybrid\switcher.ts:120:19)
    at Socket.socket.once (D:\github\pinus\examples\simple-example\game-server\node_modules\pinus\lib\connectors\hybrid\switcher.ts:99:22)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:601:20)Error
    at Object.pLogger.(anonymous function) [as error] (D:\github\pinus\examples\simple-example\game-server\node_modules\pinus-logger\lib\logger.ts:72:34)
    at process.<anonymous> (D:\github\pinus\examples\simple-example\game-server\preload.ts:32:17)
    at emitOne (events.js:116:13)
    at process.emit (events.js:211:7)
    at process._fatalException (bootstrap_node.js:391:26)

**Comment by whtiehack** [comment]
好像是node版本问题。你换用最新的 node8 或者 node10应该就解决了。

**Comment by tonyzzp** [comment]
从8升到10就可以了。
