### ISSUE TITLE
有没遇到过这种情况？master请求其他实例失败，下面是报错日志，有新的connector服务加入，通知其他connector好像失败了

### ISSUE THREAD

**Issue by ChaseRay1989** [node-pinus/pinus#757]
[2023-08-02T14:24:48.608] [ERROR] pinus - [master-server-1 watchdog.js] master watchdog request fail message: {"action":"addServer","server":{"main":"/home/gpx/app/avg-game-engine-2d/game-server/dist/game-server/app.js","id":"avg-connect-server-7974847d9f-2n7h6","host":"10.65.189.36","port":3040,"clientPort":3050,"frontend":"true","serverType":"connector","version":"1.1.12","status":1,"remoterPaths":[{"namespace":"sys","serverType":"connector","path":"/home/gpx/app/avg-game-engine-2d/node_modules/pinus/dist/lib/common/remote/frontend"}],"handlerPaths":["/home/gpx/app/avg-game-engine-2d/game-server/dist/game-server/app/servers/connector/handler"],"pid":16}}, fails: ["avg-connect-server-99458656-298gj"]Error: at Logger.pLogger. [as error] (/home/gpx/app/avg-game-engine-2d/node_modules/pinus-logger/lib/logger.ts:76:34) at CountDownLatch.cb (/home/gpx/app/avg-game-engine-2d/node_modules/pinus/lib/master/watchdog.ts:113:24) at CountDownLatch.done (/home/gpx/app/avg-game-engine-2d/node_modules/pinus/lib/util/countDownLatch.ts:41:18) at /home/gpx/app/avg-game-engine-2d/node_modules/pinus/lib/master/watchdog.ts:125:27 at MasterSocket.onMonitor (/home/gpx/app/avg-game-engine-2d/node_modules/pinus-admin/lib/master/masterSocket.ts:109:20) at Connection. (/home/gpx/app/avg-game-engine-2d/node_modules/pinus-admin/lib/master/masterAgent.ts:122:30) at Connection.emit (node:events:390:28) at Connection. (/home/gpx/app/avg-game-engine-2d/node_modules/pinus-admin/lib/protocol/mqtt/mqttServer.ts:74:24) at Connection.emit (node:events:390:28) at Connection.emitPacket (/home/gpx/app/avg-game-engine-2d/node_modules/mqtt-connection/connection.js:10:8) at Connection.emit (node:events:390:28) at addChunk (/home/gpx/app/avg-game-engine-2d/node_modules/readable-stream/lib/_stream_readable.js:291:12) at readableAddChunk (/home/gpx/app/avg-game-engine-2d/node_modules/readable-stream/lib/_stream_readable.js:278:11) at Connection.Readable.push (/home/gpx/app/avg-game-engine-2d/node_modules/readable-stream/lib/_stream_readable.js:245:10) at Connection.Duplexify._forward (/home/gpx/app/avg-game-engine-2d/node_modules/duplexify/index.js:170:26) at DestroyableTransform.onreadable (/home/gpx/app/avg-game-engine-2d/node_modules/duplexify/index.js:134:10)

**Comment by whtiehack** [comment]
可以截图. 多截点日志

**Comment by ChaseRay1989** [comment]
好像是偶尔会出现，暂时还定位不到

**Comment by ChaseRay1989** [comment]
> 可以截图. 多截点日志

好像是偶尔出现，好像就只有这么点日志
