### ISSUE TITLE
启动时logger模块报错，找不到报错原因

### ISSUE THREAD

**Issue by OTTOGH** [node-pinus/pinus#87]
[ERROR] logger - [connector-server-1 console] (node:7624) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.Error: 
    at Object.pLogger.(anonymous function) [as error] (D:\code\pinusDemo\game-server\node_modules\pinus-logger\lib\logger.ts:72:34)
    at writeOut (internal/process/warning.js:25:20)
    at output (internal/process/warning.js:79:3)
    at process.on (internal/process/warning.js:110:7)
    at process.emit (events.js:198:13)
    at process.emit (D:\code\pinusDemo\game-server\node_modules\source-map-support\source-map-support.js:465:21)
    at internal/process/warning.js:84:13
    at process._tickCallback (internal/process/next_tick.js:61:11)

**Comment by whtiehack** [comment]
这是一个警告。   可以不管。

**Comment by whtiehack** [comment]
加node启动参数 `--trace-warnings` ，可以知道是哪个模块报的警告。

**Comment by whtiehack** [comment]
已经升级到最新版本。
