### ISSUE TITLE
帮忙看一个异常TypeError: Cannot read property 'forwardMessage' of undefined

### ISSUE THREAD

**Issue by lab023** [node-pinus/pinus#93]
> |2019-10-18T21:51:59.836|ERROR|connector-server-1|pinus|connector-server-1 fail to forward message:TypeError: Cannot read property 'forwardMessage' of undefined
    at doForward (/gameServer/node_modules/pinus/lib/server/server.ts:386:54)
    at dispatch (/gameServer/node_modules/pinus/lib/server/server.ts:127:17)
    at next (/gameServer/node_modules/pinus/lib/common/service/filterService.ts:67:17)
    at FilterService.beforeFilter (/gameServer/node_modules/pinus/lib/common/service/filterService.ts:82:9)
    at beforeFilter (/gameServer/node_modules/pinus/lib/server/server.ts:294:12)
    at Server.globalHandle (/gameServer/node_modules/pinus/lib/server/server.ts:136:9)
    at ServerComponent.globalHandle (/gameServer/node_modules/pinus/lib/components/server.ts:69:21)
    at ConnectorComponent.handleMessage (/gameServer/node_modules/pinus/lib/components/connector.ts:433:21)
    at HybridSocket.socket.on (/gameServer/node_modules/pinus/lib/components/connector.ts:321:18)
    at HybridSocket.emit (events.js:198:13)
    at handleData (/gameServer/node_modules/pinus/lib/connectors/common/handler.ts:45:12)
    at Object.default_1 [as default] (/gameServer/node_modules/pinus/lib/connectors/common/handler.ts:56:9)
    at WebSocket.<anonymous> (/gameServer/node_modules/pinus/lib/connectors/hybridsocket.ts:55:24)
    at WebSocket.emit (events.js:198:13)
    at Receiver._receiver.onmessage (/gameServer/node_modules/pinus/node_modules/ws/lib/WebSocket.js:141:47)
    at Receiver.dataMessage (/gameServer/node_modules/pinus/node_modules/ws/lib/Receiver.js:380:14)
    at Receiver.getData (/gameServer/node_modules/pinus/node_modules/ws/lib/Receiver.js:330:12)
    at Receiver.startLoop (/gameServer/node_modules/pinus/node_modules/ws/lib/Receiver.js:165:16)
    at Receiver.add (/gameServer/node_modules/pinus/node_modules/ws/lib/Receiver.js:139:10)
    at TLSSocket._ultron.on (/gameServer/node_modules/pinus/node_modules/ws/lib/WebSocket.js:138:22)
    at TLSSocket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)Error:
    at Object.pLogger.(anonymous function) [as error] (/gameServer/node_modules/pinus-logger/lib/logger.ts:72:34)
    at doForward (/gameServer/node_modules/pinus/lib/server/server.ts:406:20)
    at dispatch (/gameServer/node_modules/pinus/lib/server/server.ts:127:17)
    at next (/gameServer/node_modules/pinus/lib/common/service/filterService.ts:67:17)
    at FilterService.beforeFilter (/gameServer/node_modules/pinus/lib/common/service/filterService.ts:82:9)
    at beforeFilter (/gameServer/node_modules/pinus/lib/server/server.ts:294:12)
    at Server.globalHandle (/gameServer/node_modules/pinus/lib/server/server.ts:136:9)
    at ServerComponent.globalHandle (/gameServer/node_modules/pinus/lib/components/server.ts:69:21)
    at ConnectorComponent.handleMessage (/gameServer/node_modules/pinus/lib/components/connector.ts:433:21)
    at HybridSocket.socket.on (/gameServer/node_modules/pinus/lib/components/connector.ts:321:18)
    at HybridSocket.emit (events.js:198:13)
    at handleData (/gameServer/node_modules/pinus/lib/connectors/common/handler.ts:45:12)
    at Object.default_1 [as default] (/gameServer/node_modules/pinus/lib/connectors/common/handler.ts:56:9)
    at WebSocket.<anonymous> (/gameServer/node_modules/pinus/lib/connectors/hybridsocket.ts:55:24)
    at WebSocket.emit (events.js:198:13)
    at Receiver._receiver.onmessage (/gameServer/node_modules/pinus/node_modules/ws/lib/WebSocket.js:141:47)
    at Receiver.dataMessage (/gameServer/node_modules/pinus/node_modules/ws/lib/Receiver.js:380:14)
    at Receiver.getData (/gameServer/node_modules/pinus/node_modules/ws/lib/Receiver.js:330:12)
    at Receiver.startLoop (/gameServer/node_modules/pinus/node_modules/ws/lib/Receiver.js:165:16)
    at Receiver.add (/gameServer/node_modules/pinus/node_modules/ws/lib/Receiver.js:139:10)
    at TLSSocket._ultron.on (/gameServer/node_modules/pinus/node_modules/ws/lib/WebSocket.js:138:22)
    at TLSSocket.emit (events.js:198:13)|

生产环境多次抛出，已知生产环境配置了WSS协议，开发&测试环境使用WS协议。堆栈日志没有代码引用，也不知道是哪里引起的，各位有什么建议吗？

**Comment by whtiehack** [comment]
查接口日志，是你后端进程与这个 connector-server-1的连接断掉了。
rpc不到后端进程。 

检查是哪个后端进程挂掉了。

**Comment by lab023** [comment]
> 查接口日志，是你后端进程与这个 connector-server-1的连接断掉了。
> rpc不到后端进程。
> 
> 检查是哪个后端进程挂掉了。

怪就怪在后端没挂，也没有超时日志。

**Comment by whtiehack** [comment]
你怎么判断没挂的呀？ pinus list 进程在吗？

**Comment by lab023** [comment]
> 你怎么判断没挂的呀？ pinus list 进程在吗？

进程还在，单节点游戏服还在正常工作，没有人工干预。也不知道这个问题怎么重现。

**Comment by lab023** [comment]
定位到问题了，在pinus/lib/server/server.js加打印发现是在后端调用了前方方法，所以forward失败。谢谢白总
